/**
 * Core types for the Blibli Seller API (MTA) SDK.
 *
 * These types are shared across every generated category client.
 */

/** Blibli environment (production vs staging host). */
export type BlibliEnvironment = 'production' | 'staging'

/** Credentials required to authenticate requests. */
export interface BlibliCredentials {
  /**
   * API Client Key + Secret used for HTTP Basic authentication (Authorization
   * header). Combine as `base64(clientKey:clientSecret)`.
   */
  clientKey: string
  clientSecret: string
  /** API Seller Key (Api-Seller-Key header), generated by the Seller. */
  apiSellerKey: string
  /**
   * Optional Signature Key. When set, Blibli computes a per-request HMAC-SHA256
   * signature (Signature + Signature-Time headers) over the API key.
   */
  signatureKey?: string
}

/** Per-request options. */
export interface BlibliRequestOptions {
  /** Environment override; defaults to the client-level environment. */
  environment?: BlibliEnvironment
  /** Custom base URL (overrides the environment host). */
  baseUrl?: string
  /** Override the millisecond timestamp used for the Signature-Time header. */
  timestamp?: number | string | Date
  /** Abort signal for the underlying HTTP request (Node 18+). */
  signal?: AbortSignal
}

/** Raw Blibli success/error response structures are per-API; use generics. */
export interface BlibliErrorResponse {
  code?: number | string
  errorCode?: number | string
  errors?: unknown
  message?: string
  detail?: unknown
}

/** Maps a TS payload type against a raw Blibli response (use `as T`). */
export type ApiResponse<T> = T

export class BlibliError extends Error {
  readonly code?: number | string
  readonly status?: number
  readonly body?: unknown

  constructor(
    msg: string,
    opts: { code?: number | string; status?: number; body?: unknown } = {},
  ) {
    super(msg)
    this.name = 'BlibliError'
    this.code = opts.code ?? 'unknown_error'
    this.status = opts.status
    this.body = opts.body
  }
}
